const recipes = [
	{
		image: "/Simple/cheeseburger.png",
		name: "Big and Juicy Wagyu Beef Cheeseburger",
		time: "30 Minutes",
		type: "Snack",
		id: 1,
	},
	{
		image: "/Simple/salmon.png",
		name: "Fresh Lime Roasted Salmon with Ginger Sauce",
		time: "30 Minutes",
		type: "Fish",
		id: 2,
	},
	{
		image: "/Simple/pancakes.png",
		name: "Strawberry Oatmeal Pancake with Honey Syrup",
		time: "30 Minutes",
		type: "Breakfast",
		id: 3,
	},
	{
		image: "/Simple/salad.png",
		name: "Fresh and Healthy Mixed Mayonnaise Salad",
		time: "30 Minutes",
		type: "Healthy",
		id: 4,
	},
	{
		image: "/Simple/meetballs.png",
		name: "Chicken Meatballs with Cream Cheese",
		time: "30 Minutes",
		type: "Meat",
		id: 5,
	},
	{
		image: "",
		name: "",
		time: "30 Minutes",
		type: "",
		id: 6,
	},
	{
		image: "/Simple/fruitypancake.png",
		name: "Fruity Pancake with Orange & Blueberry",
		time: "30 Minutes",
		type: "Sweet",
		id: 7,
	},
	{
		image: "/Simple/rice.png",
		name: "The Best Easy One Pot Chicken and Rice",
		time: "30 Minutes",
		type: "Snack",
		id: 8,
	},
	{
		image: "/Simple/pasta.png",
		name: "The Creamiest Creamy Chicken and Bacon Pasta",
		time: "30 Minutes",
		type: "Noodles",
		id: 9,
	},
	{
		image: "/TryRecipe/image 26.png",
		name: "Mixed Tropical Fruit Salad with Superfood Boosts ",
		time: "30 Minutes",
		type: "Healthy",
		id: 10,
	},
	{
		image: "/TryRecipe/image 26 (1).png",
		name: "Big and Juicy Wagyu Beef Cheeseburger",
		time: "30 Minutes",
		type: "Western",
		id: 11,
	},
	{
		image: "/TryRecipe/image 26 (2).png",
		name: "Healthy Japanese Fried Rice with Asparagus",
		time: "30 Minutes",
		type: "Healthy",
		id: 12,
	},
	{
		image: "/TryRecipe/image 26 (3).png",
		name: "Cauliflower Walnut Vegetarian Taco Meat",
		time: "30 Minutes",
		type: "Eastern",
		id: 13,
	},
	{
		image: "/TryRecipe/image 26 (4).png",
		name: "Rainbow Chicken Salad with Almond Honey Mustard Dressing",
		time: "30 Minutes",
		type: "Healthy",
		id: 14,
	},
	{
		image: "/TryRecipe/image 26 (5).png",
		name: "Barbeque Spicy Sandwiches with Chips ",
		time: "30 Minutes",
		type: "Snack",
		id: 15,
	},
	{
		image: "/TryRecipe/image 26 (6).png",
		name: "Firecracker Vegan Lettuce Wraps - Spicy! ",
		time: "30 Minutes",
		type: "Seafood",
		id: 16,
	},
	{
		image: "/TryRecipe/image 26 (7).png",
		name: "Chicken Ramen Soup with Mushroom ",
		time: "30 Minutes",
		type: "Japanese",
		id: 17,
	},
];

export default recipes;
